
set_property PACKAGE_PIN U19 [get_ports led_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_o_0]

set_property DRIVE 12 [get_ports led_o_0]

set_property IOSTANDARD LVCMOS33 [get_ports clk_50MHz]

create_clock -period 20.000 -name clk_50MHz -waveform {0.000 10.000} [get_ports clk_50MHz]
set_output_delay -clock [get_clocks clk_50MHz] -min -add_delay 1.900 [get_ports led_o_0]
set_output_delay -clock [get_clocks clk_50MHz] -max -add_delay 4.000 [get_ports led_o_0]

set_property PACKAGE_PIN U20 [get_ports led_o_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_o_1]

set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]
set_property PACKAGE_PIN V20 [get_ports reset_rtl_0]
set_property PACKAGE_PIN U18 [get_ports clk_50MHz]


set_property PACKAGE_PIN K14 [get_ports clk_out1_0]
set_property DRIVE 12 [get_ports clk_out1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out1_0]


set_property PACKAGE_PIN C20 [get_ports Vaux0_0_v_p]
set_property PACKAGE_PIN B20 [get_ports Vaux0_0_v_n]

set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_txd]
set_property PACKAGE_PIN G14 [get_ports UART_1_0_rxd]
set_property PACKAGE_PIN J15 [get_ports UART_1_0_txd]
set_property PACKAGE_PIN T17 [get_ports SPI_0_0_sck_io]
set_property PACKAGE_PIN N18 [get_ports SPI_0_0_ss1_o]
set_property PACKAGE_PIN P18 [get_ports SPI_0_0_ss_io]
set_property PACKAGE_PIN N17 [get_ports SPI_0_0_io0_io]
set_property PACKAGE_PIN R18 [get_ports SPI_0_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss1_o]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss2_o]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss_io]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux2_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux2_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux3_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux3_0_v_p]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN T11 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN T12 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN U12 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN P14 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN R14 [get_ports {GPIO_0_0_tri_io[5]}]
set_property PACKAGE_PIN T14 [get_ports {GPIO_0_0_tri_io[6]}]
set_property PACKAGE_PIN T15 [get_ports {GPIO_0_0_tri_io[7]}]
set_property PACKAGE_PIN P19 [get_ports SPI_0_0_ss2_o]
